steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core SDK'
    inputs:
    version: 7.x
    performMultiLevelLookup: true

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
    command: restore
    projects: '**/*.csproj'
    restoreArguments: '--force'
    feedsToUse: 'select'
    noCache: true

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'      
       
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True