parameters:
    - name: environment
    - name: configuration
stages:
  - stage: Deploy_${{parameters.environment}}
    displayName: 'Deploy to ${{parameters.environment}}'
    dependsOn: Build
    variables:
      - group: platform-api-${{parameters.configuration}}
    jobs:
    - deployment: platform_api_deploy_${{parameters.configuration}}
      displayName: API Deploy ${{parameters.environment}}
      environment: MI-Platform-${{parameters.environment}}
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none
            - checkout: none
            - task: DownloadBuildArtifacts@1
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(System.ArtifactsDirectory)'